---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-self-node-remediation-medik8s-io-v1alpha2-selfnoderemediationconfig
  failurePolicy: Fail
  name: vselfnoderemediationconfig.kb.io
  rules:
  - apiGroups:
    - self-node-remediation.medik8s.io
    apiVersions:
    - v1alpha1
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - selfnoderemediationconfigs
  sideEffects: None
