name: Pre Submit # workflow name
on: # on events
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Verify imports are sorted
      run: make test-imports

    - name: Verify there are no packages to vendor
      run: make verify-vendor

    - name: Verify bundle and manifests are updated
      run: make verify-bundle

    - name: Run checks and unit tests
      run: make test

    - name: Test container build
      run: make container-build-community
